### ISSUE TITLE
Button drawing broken with CrossAxisAlignment::Stretch

### ISSUE THREAD

**Issue by sapir** [LPGhatguy/yakui#14]
The button background color is no longer visible.

```rust
row(|| {
    button("Not stretched");
    let mut col = List::column();
    col.cross_axis_alignment = CrossAxisAlignment::Stretch;
    col.show(|| {
        button("Button 1");
        button("Button 2");
        button("Button 3");
    });
});
```

![Screenshot_20220722_150930](https://user-images.githubusercontent.com/896766/180436504-77af6618-9945-4212-aff1-a34c5da697de.png)

Also, if I move the "Not stretched" button after the column, then it's not visible at all.

**Comment by sapir** [comment]
The `Response` still detects hovering and clicking correctly.

**Comment by sapir** [comment]
If the column is placed inside a Flexible then the buttons work as expected.

**Comment by LPGhatguy** [comment]
I can see why this happens. `List` gives each child a maximum cross-axis size of infinity. That means that the column is getting a maximum size of infinity from the row, and then is trying to stretch its children to infinity.

For fun, I ported the example to Flutter:

```dart
class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      children: <Widget>[
        TextButton(child: Text("Not Stretched"), onPressed: () { }),
        Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            TextButton(child: Text("Button 1"), onPressed: () { }),
            TextButton(child: Text("Button 2"), onPressed: () { }),
            TextButton(child: Text("Button 3"), onPressed: () { }),
          ],
        ),
      ],
    );
  }
}
```

Here's what Flutter had to say about this:
> The following assertion was thrown during performLayout():
> BoxConstraints forces an infinite width.
> These invalid constraints were provided to RenderSemanticsAnnotations's layout() function by the
> following function, which probably computed the invalid constraints in question:
>  ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
> The offending constraints were:
>  BoxConstraints(w=Infinity, 0.0<=h<=Infinity)

I think we've diverged a little bit in terms of where we pass infinity vs just the actual max size, so I think this should be fixable. We allow widgets to return sizes outside of their given constraints (to "push back"), which means that truly infinite constraints are much less useful in yakui than Flutter.

**Comment by LPGhatguy** [comment]
I think we need a type like https://api.flutter.dev/flutter/widgets/IntrinsicWidth-class.html.

**Comment by LPGhatguy** [comment]
I think I've _partially_ fixed this case on master. Text alignment is a little wonky, but probably fixable:
![image](https://user-images.githubusercontent.com/654598/190023873-bbf10c40-4206-4175-ae96-35fdbd7bba88.png)

**Comment by LPGhatguy** [comment]
Alright, I ended up taking a different approach to fix this. Now, if a `List` has `CrossAxisAlignment::Stretch`, it will _also_ have a flex factor of 1. This ensures that nested lists will end up in the flexible portion of the layout pass, which gives them constrained dimensions and fixes this issue for the same reason that adding `expanded` around the column worked.
