### ISSUE TITLE
Floating/detached widgets

### ISSUE THREAD

**Issue by sapir** [LPGhatguy/yakui#18]
Is there some way to place a widget at some on-screen position and size, so its layout is detached from the parent's layout and neither takes the other into account? I thought maybe the window widget does this - the comment mentions it being a "floating window", but as far as I can tell, it's not actually implemented?

**Comment by LPGhatguy** [comment]
`Align` is probably the closest thing to this right now as far as built-in widgets go. You could also probably (ab)use `Pad` for this.

It looks like Flutter has a `Positioned` widget. We could probably port something like that to great effect.

**Comment by LPGhatguy** [comment]
I introduced the `Offset` widget as part of the work on draggables. It's not quite a floating widget like you're talking about, but a widget with `Offset` in the root could behave similarly.

**Comment by LPGhatguy** [comment]
The `Reflow` and `Layer` widgets introduced recently are the final pieces of the puzzle here.
