### ISSUE TITLE
Changing text flickers

### ISSUE THREAD

**Issue by sapir** [LPGhatguy/yakui#39]
I'm running on Linux with Intel graphics, and there's some flicker when text changes. For example, when the "text" demo starts, there's at least one frame that looks like this before it's rendered correctly:

![image](https://user-images.githubusercontent.com/896766/183058167-87c0bfba-a9ea-4ad1-bcf3-de82eaf3fcde.png)

I'm not sure, but I think, in general, each time that a new glyph is drawn, the texturing is delayed.

**Comment by LPGhatguy** [comment]
Oh, this is interesting. I saw this when making tests for the text rendering as well.

I wonder why this would happen. We update the glyph cache texture and then immediately use it. In theory, I would expect wgpu to stall the frame until all that texture stuff is done that we're using.

**Comment by LPGhatguy** [comment]
I've got an idea. I think we might need to update all of our textures and buffers before starting the command encoder in wgpu?
