### ISSUE TITLE
can't delete text or move cursor on macOS

### ISSUE THREAD

**Issue by tinaun** [LPGhatguy/yakui#40]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/2565671/183147254-9a2539da-f59e-4a15-b012-e51c34396319.png">

**Comment by LPGhatguy** [comment]
Thanks for the bug report! I don't have easy access to a macOS machine to test this out.

I wonder what this could be. We listen for arrow keys, backspace, and delete to manipulate the textbox.

**Comment by tinaun** [comment]
I believe `DeviceEvent::Key` isn't implemented on Macs - no events of that type are ever emitted by winit in my tests. changing `DeviceEvent::Key` to `WindowEvent::KeyboardInput` in `YakuiWinit::handle_event` makes text boxes handle as expected

**Comment by LPGhatguy** [comment]
Cool, thank you for looking into this.

I just pushed a commit to use `WindowEvent::KeyboardInput` instead of `DeviceEvent::Key`.
