### ISSUE TITLE
Can I make yakui look whatever I want it to look like?

### ISSUE THREAD

**Issue by Raj2032** [LPGhatguy/yakui#77]
Can I make yakui UI look whatever I want it to?

For example like pygui

![image](https://user-images.githubusercontent.com/29293830/193446571-edec49ca-7280-420a-b23d-cf5a97351c37.png)

nuclear's buttons
![image](https://user-images.githubusercontent.com/29293830/193446599-fea5fe94-085a-49b1-8edd-df56ca41c6ac.png)

etc etc?

**Comment by LPGhatguy** [comment]
Yeah! Right now the styling available with the built-in widgets is pretty limited, but custom widgets are easy to implement. The goal is that games generally will use the built-in widgets at first, and then eventually create custom widgets that fit their game's visual style.

The `yakui-widgets` crate is designed to be forkable, so you can use its widgets as a starting point. Eventually, we'll have a better slate of primitives for building very custom widgets.

**Comment by Raj2032** [comment]
@LPGhatguy I see mate thank you :)
